package view;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.TitledBorder;

import controller.ConfigsController;
import view.listeners.ConfigListener;

/**
 *
 */
public class ConfigView extends JFrame
{

    public ConfigView(ConfigsController controller)
    {
        super("Configurações");
        
        this.initComponents();
        
        new ConfigListener(this, controller);

        super.setLocationRelativeTo(null);
        super.setVisible(true);
    }
    
    public JTextField getHostField()
    {
        return this.host;
    }
    
    public JTextField getDriverField()
    {
        return this.driver;
    }
    
    public JTextField getDatabaseField()
    {
        return this.dbname;
    }
    
    public JTextField getPortField()
    {
        return this.port;
    }
    
    public JTextField getUserField()
    {
        return this.user;
    }
    
    public JPasswordField getPasswordField()
    {
        return this.password;
    }
    
    public JButton getSubmitButton()
    {
        return this.submit;
    }
    
    public JButton getCancelButton()
    {
        return this.cancel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new JPanel();
        jLabel8 = new JLabel();
        jLabel7 = new JLabel();
        jPanel2 = new JPanel();
        labelResponse = new JLabel();
        jPanel3 = new JPanel();
        jPanel4 = new JPanel();
        host = new JTextField();
        port = new JTextField();
        dbname = new JTextField();
        user = new JTextField();
        password = new JPasswordField();
        driver = new JTextField();
        submit = new JButton();
        cancel = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações de acesso ao banco de dados");
        setBackground(new Color(236, 235, 243));
        setResizable(false);

        jPanel1.setBackground(new Color(194, 1, 20));

        jLabel8.setIcon(new ImageIcon("/var/www/miscellaneous/java/BookStore/lib/img/iconfinder_6593863_and_config_configuration_files_folder_icon_64px.png")); // NOI18N

        jLabel7.setIcon(new ImageIcon("/var/www/miscellaneous/java/BookStore/lib/img/settings-gears.png")); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new Color(12, 18, 12));

        labelResponse.setFont(new Font("Dialog", 1, 15)); // NOI18N
        labelResponse.setForeground(new Color(236, 235, 243));
        labelResponse.setHorizontalAlignment(SwingConstants.CENTER);
        labelResponse.setToolTipText("");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelResponse, GroupLayout.PREFERRED_SIZE, 264, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(labelResponse, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new Color(173, 30, 45));

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new Color(236, 235, 243));

        host.setBackground(new Color(236, 235, 243));
        host.setForeground(new Color(12, 18, 12));
        host.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "Servidor/IP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        host.setCaretColor(new Color(194, 1, 20));
        host.setSelectedTextColor(new Color(236, 235, 243));
        host.setSelectionColor(new Color(152, 58, 69));

        port.setBackground(new Color(236, 235, 243));
        port.setForeground(new Color(12, 18, 12));
        port.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "Porta", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        port.setCaretColor(new Color(194, 1, 20));
        port.setSelectedTextColor(new Color(236, 235, 243));
        port.setSelectionColor(new Color(152, 58, 69));

        dbname.setBackground(new Color(236, 235, 243));
        dbname.setForeground(new Color(12, 18, 12));
        dbname.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "Base de Dados", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        dbname.setCaretColor(new Color(194, 1, 20));
        dbname.setSelectedTextColor(new Color(236, 235, 243));
        dbname.setSelectionColor(new Color(152, 58, 69));

        user.setBackground(new Color(236, 235, 243));
        user.setForeground(new Color(12, 18, 12));
        user.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "Usuário", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        user.setCaretColor(new Color(194, 1, 20));
        user.setSelectedTextColor(new Color(236, 235, 243));
        user.setSelectionColor(new Color(152, 58, 69));

        password.setBackground(new Color(236, 235, 243));
        password.setForeground(new Color(12, 18, 12));
        password.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "Senha", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        password.setCaretColor(new Color(194, 1, 20));
        password.setSelectedTextColor(new Color(236, 235, 243));
        password.setSelectionColor(new Color(152, 58, 69));

        driver.setEditable(false);
        driver.setBackground(new Color(236, 235, 243));
        driver.setForeground(new Color(12, 18, 12));
        driver.setText("mysql");
        driver.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "Banco", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        driver.setCaretColor(new Color(194, 1, 20));
        driver.setSelectedTextColor(new Color(236, 235, 243));
        driver.setSelectionColor(new Color(152, 58, 69));

        submit.setBackground(new Color(194, 1, 20));
        submit.setFont(new Font("Dialog", 1, 15)); // NOI18N
        submit.setForeground(new Color(12, 18, 12));
        submit.setText("Save");
        submit.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        submit.setContentAreaFilled(false);
        submit.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        submit.setFocusPainted(false);
        submit.setVerifyInputWhenFocusTarget(false);

        cancel.setBackground(new Color(194, 1, 20));
        cancel.setFont(new Font("Dialog", 1, 15)); // NOI18N
        cancel.setForeground(new Color(12, 18, 12));
        cancel.setText("Cancel");
        cancel.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        cancel.setContentAreaFilled(false);
        cancel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        cancel.setFocusPainted(false);

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(submit, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
                    .addComponent(driver, GroupLayout.Alignment.LEADING)
                    .addComponent(password, GroupLayout.Alignment.LEADING)
                    .addComponent(user, GroupLayout.Alignment.LEADING)
                    .addComponent(dbname, GroupLayout.Alignment.LEADING)
                    .addComponent(port, GroupLayout.Alignment.LEADING)
                    .addComponent(host, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(host, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(port, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dbname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(driver, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancel;
    private JTextField dbname;
    private JTextField driver;
    private JTextField host;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JLabel labelResponse;
    private JPasswordField password;
    private JTextField port;
    private JButton submit;
    private JTextField user;
    // End of variables declaration//GEN-END:variables
}