package view;

import model.factories.ConfigFactory;
import java.awt.event.*;
import java.io.IOException;
import javax.swing.*;
import model.ConfigDataBase;
import model.dao.ConfigDAO;
import org.json.JSONObject;

/**
 *
 *
 */
public class ConfigView extends JFrame
{

    public ConfigView()
    {
        super("Configurações");
        initComponents();
        initListeners();

        loadFields();

        super.setLocationRelativeTo(null);
        super.setVisible(true);
    }

    private void loadFields()
    {
        try
        {
            JSONObject json = new ConfigDAO().read();
            setFields(json);
        } catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void setFields(JSONObject json)
    {
        this.fieldHost    .setText(json.getString("host"));
        this.fieldPort    .setText(json.getString("port"));
        this.fieldDatabase.setText(json.getString("database"));
        this.fieldUser    .setText(json.getString("user"));
        this.fieldPassword.setText(json.getString("pass"));
        this.fieldDBName  .setText(json.getString("dbName"));
    }

    public JSONObject getJSON()
    {
        JSONObject json = new JSONObject();

        json.put("host",    this.fieldHost.getText());
        json.put("port",    this.fieldPort.getText());
        json.put("database",this.fieldDatabase.getText());
        json.put("user",    this.fieldUser.getText());
        json.put("pass",    String.valueOf( this.fieldPassword.getPassword() ));
        json.put("dbName",  this.fieldDBName.getText());

        return json;
    }

    private void initListeners()
    {
        this.buttonCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        this.buttonSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                JSONObject json       = getJSON();
                ConfigDataBase config = new ConfigFactory().buildFrom(json);
                try {
                    new ConfigDAO().write(config);
                    labelResponse.setText("Configurações salvas.");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelResponse = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fieldHost = new javax.swing.JTextField();
        fieldPort = new javax.swing.JTextField();
        fieldDatabase = new javax.swing.JTextField();
        fieldUser = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        fieldDBName = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações de acesso ao banco de dados");
        setBackground(new java.awt.Color(236, 235, 243));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(194, 1, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconfinder_6593863_and_config_configuration_files_folder_icon_64px.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings-gears.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(12, 18, 12));

        labelResponse.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        labelResponse.setForeground(new java.awt.Color(236, 235, 243));
        labelResponse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResponse.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(labelResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(173, 30, 45));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(236, 235, 243));

        fieldHost.setBackground(new java.awt.Color(236, 235, 243));
        fieldHost.setForeground(new java.awt.Color(12, 18, 12));
        fieldHost.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 18, 12), 2), "Servidor/IP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldHost.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldHost.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldHost.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldPort.setBackground(new java.awt.Color(236, 235, 243));
        fieldPort.setForeground(new java.awt.Color(12, 18, 12));
        fieldPort.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 18, 12), 2), "Porta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldPort.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldPort.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldPort.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldDatabase.setBackground(new java.awt.Color(236, 235, 243));
        fieldDatabase.setForeground(new java.awt.Color(12, 18, 12));
        fieldDatabase.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 18, 12), 2), "Base de Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldDatabase.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldDatabase.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldDatabase.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldUser.setBackground(new java.awt.Color(236, 235, 243));
        fieldUser.setForeground(new java.awt.Color(12, 18, 12));
        fieldUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 18, 12), 2), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldUser.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldUser.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldUser.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldPassword.setBackground(new java.awt.Color(236, 235, 243));
        fieldPassword.setForeground(new java.awt.Color(12, 18, 12));
        fieldPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 18, 12), 2), "Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldPassword.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldPassword.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldPassword.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldDBName.setEditable(false);
        fieldDBName.setBackground(new java.awt.Color(236, 235, 243));
        fieldDBName.setForeground(new java.awt.Color(12, 18, 12));
        fieldDBName.setText("mysql");
        fieldDBName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 18, 12), 2), "Banco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldDBName.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldDBName.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldDBName.setSelectionColor(new java.awt.Color(152, 58, 69));

        buttonSave.setBackground(new java.awt.Color(194, 1, 20));
        buttonSave.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(12, 18, 12));
        buttonSave.setText("Salvar");
        buttonSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 1, 20), 3));
        buttonSave.setContentAreaFilled(false);
        buttonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSave.setFocusPainted(false);
        buttonSave.setVerifyInputWhenFocusTarget(false);

        buttonCancel.setBackground(new java.awt.Color(194, 1, 20));
        buttonCancel.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(12, 18, 12));
        buttonCancel.setText("Cancelar");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 1, 20), 3));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCancel.setFocusPainted(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldDBName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldUser, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldDatabase, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPort, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldHost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextField fieldDBName;
    private javax.swing.JTextField fieldDatabase;
    private javax.swing.JTextField fieldHost;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldPort;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelResponse;
    // End of variables declaration//GEN-END:variables
}