package view;

import java.awt.*;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

import controller.PublishingsController;
import view.listeners.PublishingListener;

/**
 *
 */
public class PublishingView extends JFrame
{

    public PublishingView(PublishingsController controller)
    {
        super("Editoras");

        this.initComponents();

        new PublishingListener(this, controller);

        super.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        super.setLocationRelativeTo(null);
        super.setVisible(true);
    }
    
    public JTextField getNameField()
    {
        return this.name;
    }
    
    public JTextField getIdField()
    {
        return this.pubID;
    }

    public JFormattedTextField getUfField()
    {
        return this.uf;
    }
    
    public JFormattedTextField getCityField()
    {
        return this.city;
    }

    public JFormattedTextField getDistrictField()
    {
        return this.district;
    }
    
    public JFormattedTextField getStreetField()
    {
        return this.street;
    }

    public JFormattedTextField getNumberField()
    {
        return this.number;
    }
    
    public JFormattedTextField getCepField()
    {
        return this.cep;
    }

    public JTextArea getComplField()
    {
        return this.complement;
    }
    
    public JButton getAddButton()
    {
        return this.add;
    }

    public JButton getUpdateButton()
    {
        return this.update;
    }
    
    public JButton getDeleteButton()
    {
        return this.delete;
    }
    
    public JButton getCloseButton()
    {
        return this.close;
    }

    public JButton getSubmitButton()
    {
        return this.submit;
    }
    
    public JButton getCancelButton()
    {
        return this.cancel;
    }

    public JTable getTable()
    {
        return this.table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel5 = new JPanel();
        jPanel4 = new JPanel();
        add = new JButton();
        update = new JButton();
        delete = new JButton();
        jScrollPane1 = new JScrollPane();
        table = new JTable();
        jPanel7 = new JPanel();
        jPanel6 = new JPanel();
        close = new JButton();
        jPanel10 = new JPanel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jPanel11 = new JPanel();
        name = new JTextField();
        pubID = new JTextField();
        jPanel2 = new JPanel();
        city = new JFormattedTextField();
        district = new JFormattedTextField();
        street = new JFormattedTextField();
        jScrollPane2 = new JScrollPane();
        complement = new JTextArea();
        jPanel3 = new JPanel();
        uf = new JFormattedTextField();
        number = new JFormattedTextField();
        cep = new JFormattedTextField();
        submit = new JButton();
        cancel = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new Color(236, 235, 243));

        jPanel4.setBackground(new Color(236, 235, 243));

        add.setForeground(new Color(12, 18, 12));
        add.setText("Novo");
        add.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        add.setContentAreaFilled(false);
        add.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        add.setFocusPainted(false);

        update.setForeground(new Color(12, 18, 12));
        update.setText("Editar");
        update.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        update.setContentAreaFilled(false);
        update.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        update.setFocusPainted(false);

        delete.setForeground(new Color(12, 18, 12));
        delete.setText("Excluir");
        delete.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        delete.setContentAreaFilled(false);
        delete.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        delete.setFocusPainted(false);

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(delete, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jScrollPane1.setBackground(new Color(236, 235, 243));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 3));

        table.setBackground(new Color(236, 235, 243));
        table.setForeground(new Color(12, 18, 12));
        table.setModel(new DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Nome da Cia.", "UF/Estado", "Cidade", "Bairro", "CEP", "Rua", "Número", "Complemento"
            }
        )
        {
            Class[] types = new Class []
            {
                String.class, String.class, String.class, String.class, String.class, String.class, Integer.class, String.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.setFillsViewportHeight(true);
        table.setGridColor(new Color(12, 18, 12));
        table.setSelectionBackground(new Color(152, 58, 69));
        table.setSelectionForeground(new Color(236, 235, 243));
        table.setShowGrid(true);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0)
        {
            table.getColumnModel().getColumn(0).setPreferredWidth(300);
            table.getColumnModel().getColumn(1).setPreferredWidth(100);
            table.getColumnModel().getColumn(2).setPreferredWidth(200);
            table.getColumnModel().getColumn(3).setPreferredWidth(200);
            table.getColumnModel().getColumn(4).setPreferredWidth(100);
            table.getColumnModel().getColumn(5).setPreferredWidth(200);
            table.getColumnModel().getColumn(6).setPreferredWidth(100);
            table.getColumnModel().getColumn(7).setPreferredWidth(500);
        }

        jPanel7.setBackground(new Color(173, 30, 45));

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new Color(12, 18, 12));
        jPanel6.setPreferredSize(new Dimension(118, 35));

        close.setFont(new Font("Dialog", 1, 14)); // NOI18N
        close.setForeground(new Color(236, 235, 243));
        close.setText("Close");
        close.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        close.setContentAreaFilled(false);
        close.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        close.setFocusPainted(false);

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(close, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new Color(194, 1, 20));

        jLabel3.setIcon(new ImageIcon("/var/www/miscellaneous/java/BookStore/lib/img/bookstore.png")); // NOI18N

        jLabel4.setIcon(new ImageIcon("/var/www/miscellaneous/java/BookStore/lib/img/bookstore.png")); // NOI18N

        GroupLayout jPanel10Layout = new GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        jPanel11.setBackground(new Color(236, 235, 243));
        jPanel11.setBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 3));

        name.setBackground(new Color(236, 235, 243));
        name.setForeground(new Color(12, 18, 12));
        name.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "Editora", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        name.setCaretColor(new Color(194, 1, 20));
        name.setSelectedTextColor(new Color(236, 235, 243));
        name.setSelectionColor(new Color(152, 58, 69));

        pubID.setEditable(false);
        pubID.setBackground(new Color(236, 235, 243));
        pubID.setForeground(new Color(12, 18, 12));
        pubID.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(12, 18, 12), 2), "ID", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        pubID.setCaretColor(new Color(194, 1, 20));
        pubID.setSelectedTextColor(new Color(236, 235, 243));
        pubID.setSelectionColor(new Color(152, 58, 69));

        jPanel2.setBackground(new Color(236, 235, 243));

        city.setBackground(new Color(236, 235, 243));
        city.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2), "Cidade", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        city.setForeground(new Color(12, 18, 12));
        city.setCaretColor(new Color(194, 1, 20));
        city.setSelectedTextColor(new Color(236, 235, 243));
        city.setSelectionColor(new Color(152, 58, 69));

        district.setBackground(new Color(236, 235, 243));
        district.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2), "Bairro", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        district.setForeground(new Color(12, 18, 12));
        district.setCaretColor(new Color(194, 1, 20));
        district.setSelectedTextColor(new Color(236, 235, 243));
        district.setSelectionColor(new Color(152, 58, 69));

        street.setBackground(new Color(236, 235, 243));
        street.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2), "Rua", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        street.setForeground(new Color(12, 18, 12));
        street.setCaretColor(new Color(194, 1, 20));
        street.setSelectedTextColor(new Color(236, 235, 243));
        street.setSelectionColor(new Color(152, 58, 69));

        complement.setBackground(new Color(236, 235, 243));
        complement.setColumns(20);
        complement.setForeground(new Color(12, 18, 12));
        complement.setRows(5);
        complement.setTabSize(4);
        complement.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2), "Complemento", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        complement.setCaretColor(new Color(194, 1, 20));
        complement.setSelectedTextColor(new Color(236, 235, 243));
        complement.setSelectionColor(new Color(152, 58, 69));
        jScrollPane2.setViewportView(complement);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(street, GroupLayout.Alignment.TRAILING)
                    .addComponent(district)
                    .addComponent(city, GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(city, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(district, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(street, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new Color(236, 235, 243));

        uf.setBackground(new Color(236, 235, 243));
        uf.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2), "UF/Estado", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        uf.setForeground(new Color(12, 18, 12));
        try
        {
            uf.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("UU")));
        } catch (ParseException ex)
        {
            ex.printStackTrace();
        }
        uf.setCaretColor(new Color(194, 1, 20));
        uf.setSelectedTextColor(new Color(236, 235, 243));
        uf.setSelectionColor(new Color(152, 58, 69));

        number.setBackground(new Color(236, 235, 243));
        number.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2), "Número", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        number.setForeground(new Color(12, 18, 12));
        number.setCaretColor(new Color(194, 1, 20));
        number.setSelectedTextColor(new Color(236, 235, 243));
        number.setSelectionColor(new Color(152, 58, 69));

        cep.setBackground(new Color(236, 235, 243));
        cep.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2), "CEP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Liberation Sans", 0, 15), new Color(12, 18, 12))); // NOI18N
        cep.setForeground(new Color(12, 18, 12));
        try
        {
            cep.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("#####-###")));
        } catch (ParseException ex)
        {
            ex.printStackTrace();
        }
        cep.setCaretColor(new Color(194, 1, 20));
        cep.setSelectedTextColor(new Color(236, 235, 243));
        cep.setSelectionColor(new Color(152, 58, 69));

        submit.setBackground(new Color(236, 235, 243));
        submit.setFont(new Font("Dialog", 1, 14)); // NOI18N
        submit.setForeground(new Color(12, 18, 12));
        submit.setText("Submit");
        submit.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        submit.setContentAreaFilled(false);
        submit.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        submit.setFocusPainted(false);

        cancel.setBackground(new Color(236, 235, 243));
        cancel.setFont(new Font("Dialog", 1, 14)); // NOI18N
        cancel.setForeground(new Color(12, 18, 12));
        cancel.setText("Cancel");
        cancel.setBorder(BorderFactory.createLineBorder(new Color(194, 1, 20), 3));
        cancel.setContentAreaFilled(false);
        cancel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        cancel.setFocusPainted(false);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(number)
                    .addComponent(cep)
                    .addComponent(uf, GroupLayout.Alignment.TRAILING)
                    .addComponent(submit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel, GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cep, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(name, GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pubID, GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pubID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 217, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton add;
    private JButton cancel;
    private JFormattedTextField cep;
    private JFormattedTextField city;
    private JButton close;
    private JTextArea complement;
    private JButton delete;
    private JFormattedTextField district;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JTextField name;
    private JFormattedTextField number;
    private JTextField pubID;
    private JFormattedTextField street;
    private JButton submit;
    private JTable table;
    private JFormattedTextField uf;
    private JButton update;
    // End of variables declaration//GEN-END:variables
}