/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author cassiano
 */
public class BookPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public BookPanel() {
        initComponents();
        initListeners();

    }
    
    private void initListeners(){
//        this.buttonSave.addActionListener(new ActionListener() {

//            @Override
//            public void actionPerformed(ActionEvent e) {
//                System.out.println("Salvou");
//            }
//        });
        
        this.buttonCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Cancelou");
            }
        });
        
        this.buttonShowAuthor.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Mostrou autor");
            }
        });
        
        this.buttonShowPublishing.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Mostrou editora");
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fieldTitle = new javax.swing.JFormattedTextField();
        fieldGender = new javax.swing.JFormattedTextField();
        fieldPages = new javax.swing.JFormattedTextField();
        fieldFinishing = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        fieldYear = new javax.swing.JFormattedTextField();
        fieldCode = new javax.swing.JFormattedTextField();
        fieldSell = new javax.swing.JFormattedTextField();
        fieldBuy = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        fieldID = new javax.swing.JFormattedTextField();
        fieldPublishing = new javax.swing.JFormattedTextField();
        fieldAuthor = new javax.swing.JFormattedTextField();
        buttonShowAuthor = new javax.swing.JButton();
        buttonShowPublishing = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(236, 235, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 18, 12), 3));

        jPanel2.setBackground(new java.awt.Color(236, 235, 243));

        fieldTitle.setBackground(new java.awt.Color(236, 235, 243));
        fieldTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Título", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldTitle.setForeground(new java.awt.Color(12, 18, 12));
        fieldTitle.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldTitle.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldTitle.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldGender.setBackground(new java.awt.Color(236, 235, 243));
        fieldGender.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Gênero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldGender.setForeground(new java.awt.Color(12, 18, 12));
        fieldGender.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldGender.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldGender.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldPages.setBackground(new java.awt.Color(236, 235, 243));
        fieldPages.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Nº de Páginas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldPages.setForeground(new java.awt.Color(12, 18, 12));
        fieldPages.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldPages.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldPages.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldFinishing.setBackground(new java.awt.Color(236, 235, 243));
        fieldFinishing.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Acabamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldFinishing.setForeground(new java.awt.Color(12, 18, 12));
        fieldFinishing.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldFinishing.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldFinishing.setSelectionColor(new java.awt.Color(152, 58, 69));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(fieldPages)
                    .addComponent(fieldFinishing, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldTitle))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldFinishing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(236, 235, 243));

        fieldYear.setBackground(new java.awt.Color(236, 235, 243));
        fieldYear.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Ano de Lançamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldYear.setForeground(new java.awt.Color(12, 18, 12));
        fieldYear.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldYear.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldYear.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldCode.setBackground(new java.awt.Color(236, 235, 243));
        fieldCode.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Código de Barras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldCode.setForeground(new java.awt.Color(12, 18, 12));
        fieldCode.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldCode.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldCode.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldSell.setBackground(new java.awt.Color(236, 235, 243));
        fieldSell.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Valor de Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldSell.setForeground(new java.awt.Color(12, 18, 12));
        fieldSell.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldSell.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldSell.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldBuy.setBackground(new java.awt.Color(236, 235, 243));
        fieldBuy.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Valor de Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldBuy.setForeground(new java.awt.Color(12, 18, 12));
        fieldBuy.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldBuy.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldBuy.setSelectionColor(new java.awt.Color(152, 58, 69));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldYear)
                    .addComponent(fieldCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(fieldSell)
                    .addComponent(fieldBuy, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(236, 235, 243));

        fieldID.setEditable(false);
        fieldID.setBackground(new java.awt.Color(236, 235, 243));
        fieldID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ID do Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldID.setForeground(new java.awt.Color(12, 18, 12));
        fieldID.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldID.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldID.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldPublishing.setEditable(false);
        fieldPublishing.setBackground(new java.awt.Color(236, 235, 243));
        fieldPublishing.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ID da Editora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldPublishing.setForeground(new java.awt.Color(12, 18, 12));
        fieldPublishing.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldPublishing.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldPublishing.setSelectionColor(new java.awt.Color(152, 58, 69));

        fieldAuthor.setEditable(false);
        fieldAuthor.setBackground(new java.awt.Color(236, 235, 243));
        fieldAuthor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ID do Autor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(12, 18, 12))); // NOI18N
        fieldAuthor.setForeground(new java.awt.Color(12, 18, 12));
        fieldAuthor.setCaretColor(new java.awt.Color(194, 1, 20));
        fieldAuthor.setSelectedTextColor(new java.awt.Color(236, 235, 243));
        fieldAuthor.setSelectionColor(new java.awt.Color(152, 58, 69));

        buttonShowAuthor.setBackground(new java.awt.Color(236, 235, 243));
        buttonShowAuthor.setForeground(new java.awt.Color(12, 18, 12));
        buttonShowAuthor.setText("Ver");
        buttonShowAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        buttonShowAuthor.setContentAreaFilled(false);
        buttonShowAuthor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonShowPublishing.setBackground(new java.awt.Color(236, 235, 243));
        buttonShowPublishing.setForeground(new java.awt.Color(12, 18, 12));
        buttonShowPublishing.setText("Ver");
        buttonShowPublishing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        buttonShowPublishing.setContentAreaFilled(false);
        buttonShowPublishing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonSave.setBackground(new java.awt.Color(236, 235, 243));
        buttonSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(12, 18, 12));
        buttonSave.setText("Salvar");
        buttonSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 1, 20), 3));
        buttonSave.setContentAreaFilled(false);
        buttonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonCancel.setBackground(new java.awt.Color(236, 235, 243));
        buttonCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(12, 18, 12));
        buttonCancel.setText("Cancelar");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 1, 20), 3));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldID)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldPublishing, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldAuthor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(buttonShowAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonShowPublishing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonShowAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPublishing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonShowPublishing, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        buttonSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                System.out.println("Salvou com Code Custom");
            }

        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonShowAuthor;
    private javax.swing.JButton buttonShowPublishing;
    private javax.swing.JFormattedTextField fieldAuthor;
    private javax.swing.JFormattedTextField fieldBuy;
    private javax.swing.JFormattedTextField fieldCode;
    private javax.swing.JFormattedTextField fieldFinishing;
    private javax.swing.JFormattedTextField fieldGender;
    private javax.swing.JFormattedTextField fieldID;
    private javax.swing.JFormattedTextField fieldPages;
    private javax.swing.JFormattedTextField fieldPublishing;
    private javax.swing.JFormattedTextField fieldSell;
    private javax.swing.JFormattedTextField fieldTitle;
    private javax.swing.JFormattedTextField fieldYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
